# Config file for automatic testing at travis-ci.org

sudo: false
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

env:
- PYTEST=3
- PYTEST=4
- PYTEST=5
- PYTEST=master

matrix:
  include:
    - python: 'pypy'
      dist: trusty
      env: PYTEST=4
    - python: 2.7
      env: PYTEST=3
    - python: 2.7
      env: PYTEST=4
    - python: 3.4
      env: PYTEST=3
    - python: 3.4
      env: PYTEST=4

jobs:
  allow_failures:
    - env: PYTEST=master

install:
  # coveralls-python needs a newer setuptools to install from git
  - "[[ $TRAVIS_PYTHON_VERSION == pypy ]] || pip install --upgrade setuptools pip"
  # Using the coveralls-python master until parallel builds support is released
  # See: https://github.com/coveralls-clients/coveralls-python/commit/7ba3a5
  - "[[ $TRAVIS_PYTHON_VERSION == pypy ]] || pip install git+https://github.com/coveralls-clients/coveralls-python"
  - pip install tox-travis coverage
script:
  - tox -v
  - coverage combine
after_success:
  - "[[ $TRAVIS_PYTHON_VERSION == pypy ]] || COVERALLS_PARALLEL=true coveralls"

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
